### ISSUE TITLE
Tiempo de carga

### ISSUE THREAD

**Issue by jose7995** [claudio-familia/student-risk-hero#12]
Al ingresar los credenciales de manera incorrecta, la página se mantiene cargando y no se puede regresar al inicio.

Tipo de error: Leve

![Tiempo de carga2](https://user-images.githubusercontent.com/86148524/206788437-d166a631-7eb9-4d90-ac58-e3aeb13da51b.jpg)

**Comment by claudio-familia** [comment]
Issue was resolved
